version: '3'
services:
    app:
      build:
        context: .
        args:
        - BRANCH=${BRANCH-master}
      image: ninech/netbox:${BRANCH-latest}
      depends_on:
      - postgres
      env_file: netbox.env
      volumes:
      - ./startup_scripts:/opt/netbox/startup_scripts:ro
      - ./initializers:/opt/netbox/initializers:ro
      - ./configuration:/etc/netbox/config:ro
      command:
      - ./manage.py
      - test
    postgres:
      image: postgres:10.2-alpine
      env_file: postgres.env
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
