on:
  push:
    branches-ignore:
      - release

jobs:
  build:
    strategy:
      matrix:
        build_cmd:
        - ./build-latest.sh
        - PRERELEASE=true ./build-latest.sh
        - ./build-branches.sh
        docker_from:
        - '' # use the default of the DOCKERFILE
        - python:3.7-alpine
        - python:3.8-alpine
        # - python:3.9-rc-alpine # Netbox does not work with Python 3.9 yet.
      fail-fast: false
    runs-on: ubuntu-latest
    name: Builds new Netbox Docker Images
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build the image from '${{ matrix.docker_from }}' with '${{ matrix.build_cmd }}'
      run: ${{ matrix.build_cmd }}
      env:
        DOCKER_FROM: ${{ matrix.docker_from }}
        GH_ACTION: enable
    - name: Test the image
      run: IMAGE="${FINAL_DOCKER_TAG}" ./test.sh
